AWSTemplateFormatVersion: 2010-09-09
Description: "Create SQS queue"
Metadata:
  Backstage:
    Entities:
      - apiVersion: backstage.io/v1alpha1
        kind: Resource
        metadata:
          name: {name}
          description: SQS queue {name}
        spec:
          type: queue
          owner: supplier-management-team
          
Parameters:
  QueueName:
    Type: String
    
Resources:
  SqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      KmsMasterKeyId: alias/aws/sqs
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 345600
      QueueName: !Ref QueueName
      ReceiveMessageWaitTimeSeconds: 0
      VisibilityTimeout: 30
